apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ferp2qonm-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ferp2qonm-go 
  name: ferp2qonm-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ferp2qonm-go 
