apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ferp2qonm-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:030fec88752b444be7c4b10835233fcd1e579fcf@sha256:5b5e163a0aae7c190e35f0140dfacd005784061f81bc5b1f0f90fa2eb1fb247f
          name: container-image
